services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: goit-pythonweb-hw-10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
