"""add email verification flag to User

Revision ID: 8e43aa2bcbb0
Revises: 141bf7951f70
Create Date: 2025-11-23 13:33:38.584956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e43aa2bcbb0"
down_revision: Union[str, Sequence[str], None] = "141bf7951f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))

    # Step 2: Set False for all existing rows
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")

    # Step 3: Make column NOT NULL
    op.alter_column(
        "users", "email_verified", nullable=False, existing_type=sa.Boolean()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
